version: '3.4'

networks:
    contactapi-network:

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: contact-mssql

  contact.api:
    image: ${DOCKER_REGISTRY-}contact
    container_name: contact-api

    build:
      context: .
      dockerfile: Contact.Api/Dockerfile
    depends_on:
      - sqldata

    networks:
      - contactapi-network